package main

import (
	"fmt"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	"github.com/SIT-board/board_backend/controller"
	"github.com/SIT-board/board_backend/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/SIT-board/board_backend/global"
)

// @contact.name   API Support
// @contact.url    http://www.swagger.io/support
// @contact.email  support@swagger.io

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html
func main() {

	// programatically set swagger info
	docs.SwaggerInfo.Title = "SIT-board api"
	docs.SwaggerInfo.Description = "This is a server of SIT-board."
	docs.SwaggerInfo.Version = "1.0"
	docs.SwaggerInfo.Host = "github.com/SIT-board"
	docs.SwaggerInfo.BasePath = "/v2"
	docs.SwaggerInfo.Schemes = []string{"http", "https"}

	r := gin.Default()

	config := global.GetDefaultConfig()
	(&controller.Controller{
		Engine: r,
		Config: config,
	}).Init()

	// use ginSwagger middleware to serve the API docs
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	server := config.Server
	r.Run(fmt.Sprintf("%s:%d", server.ListenIp, server.ListenPort))
}
